name: Run Flask App and Test Client

on: [push]  # Запускать при каждом push

jobs:
  test:
    runs-on: ubuntu-latest  # Используем Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Flask app (some_app.py)
        run: |
          python some_app.py &  # Запуск в фоновом режиме
          sleep 30  # Ждём, пока сервер запустится

      - name: Run client test (client.py)
        run: python client.py